FROM gcr.io/distroless/static-debian12:nonroot
ARG TARGETPLATFORM
COPY $TARGETPLATFORM/finfocus-plugin-opencost /finfocus-plugin-opencost
COPY config.example.yaml /etc/finfocus/opencost/config.example.yaml
COPY plugin.manifest.json /etc/finfocus/opencost/plugin.manifest.json
USER nonroot:nonroot
ENTRYPOINT ["/finfocus-plugin-opencost"]
