opencost:
  prometheus:
    internal:
      enabled: true
      namespaceName: prometheus-system
      serviceName: prometheus-server
      port: 80
  customPricing:
    enabled: true
    createConfigmap: true
    provider: custom
    costModel:
      description: spike fixed rates
      CPU: "2.0"
      spotCPU: "2.0"
      RAM: "1.0"
      spotRAM: "1.0"
      GPU: "10.0"
      storage: "0.25"
      zoneNetworkEgress: "0.01"
      regionNetworkEgress: "0.01"
      internetNetworkEgress: "0.01"
  ui:
    enabled: false
